name: React Frontend CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: echo "No tests to run. Skipping..."

      - name: Build React app
        run: npm run build

      - name: Trigger Netlify Deploy Hook
        run: curl -X POST ${{ secrets.NETLIFY_DEPLOY_HOOK }}
